# Generated by Django 5.2.18 on 2026-10-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150)),
                ('password', models.CharField(db_column='contrasena_hash', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('Emprendedora', 'Emprendedora'), ('Cliente', 'Cliente'), ('Operaria', 'Operaria')], max_length=20)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
                'indexes': [models.Index(fields=['rol'], name='idx_usuario_rol'), models.Index(fields=['is_active'], name='idx_usuario_activo')],
                'constraints': [models.UniqueConstraint(fields=('correo',), name='uq_usuario_correo'), models.CheckConstraint(condition=models.Q(('rol__in', ['Emprendedora', 'Cliente', 'Operaria'])), name='ck_usuario_rol'), models.CheckConstraint(condition=models.Q(('telefono__isnull', True), ('telefono__regex', '^[0-9+ ()-]{7,20}$'), _connector='OR'), name='ck_usuario_telefono'), models.CheckConstraint(condition=models.Q(('direccion__isnull', True), models.Q(('direccion', ''), _negated=True), _connector='OR'), name='ck_usuario_direccion')],
            },
        ),
    ]
